In [ ]:
%matplotlib inline
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import numpy as np

In [13]:
def conversion(sex):
    if sex == 'M':
        sex = 0
    elif sex == 'F':
        sex = 1
    else:
        sex = 2
    
    return sex

In [12]:
data = pd.read_csv('abalone_dataset.csv')
data.head(10)

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,type
0,M,0.535,0.420,0.150,0.6995,0.2575,0.1530,0.2400,3
1,I,0.510,0.380,0.115,0.5155,0.2150,0.1135,0.1660,1
2,I,0.185,0.130,0.045,0.0290,0.0120,0.0075,0.0095,1
3,M,0.550,0.450,0.170,0.8100,0.3170,0.1570,0.2200,3
4,I,0.535,0.415,0.150,0.5765,0.3595,0.1350,0.2250,1
5,F,0.700,0.575,0.205,1.7730,0.6050,0.4470,0.5380,3
6,M,0.400,0.305,0.085,0.2970,0.1080,0.0705,0.1000,2
7,F,0.620,0.480,0.165,1.0125,0.5325,0.4365,0.3240,2
8,M,0.655,0.515,0.200,1.3730,0.4430,0.3375,0.4900,3
9,F,0.595,0.475,0.165,1.1480,0.4440,0.2140,0.3700,2

In [14]:
data['sex'] = data['sex'].apply(conversion)

In [15]:
data.head(10)

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,type
0,0,0.535,0.420,0.150,0.6995,0.2575,0.1530,0.2400,3
1,2,0.510,0.380,0.115,0.5155,0.2150,0.1135,0.1660,1
2,2,0.185,0.130,0.045,0.0290,0.0120,0.0075,0.0095,1
3,0,0.550,0.450,0.170,0.8100,0.3170,0.1570,0.2200,3
4,2,0.535,0.415,0.150,0.5765,0.3595,0.1350,0.2250,1
5,1,0.700,0.575,0.205,1.7730,0.6050,0.4470,0.5380,3
6,0,0.400,0.305,0.085,0.2970,0.1080,0.0705,0.1000,2
7,1,0.620,0.480,0.165,1.0125,0.5325,0.4365,0.3240,2
8,0,0.655,0.515,0.200,1.3730,0.4430,0.3375,0.4900,3
9,1,0.595,0.475,0.165,1.1480,0.4440,0.2140,0.3700,2

In [27]:
values = data.values
values

array([[0.    , 0.535 , 0.42  , ..., 0.153 , 0.24  , 3.    ],
       [2.    , 0.51  , 0.38  , ..., 0.1135, 0.166 , 1.    ],
       [2.    , 0.185 , 0.13  , ..., 0.0075, 0.0095, 1.    ],
       ...,
       [2.    , 0.45  , 0.34  , ..., 0.1075, 0.12  , 1.    ],
       [1.    , 0.52  , 0.41  , ..., 0.1835, 0.235 , 3.    ],
       [1.    , 0.64  , 0.48  , ..., 0.2345, 0.353 , 2.    ]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split()